/*
* Copyright (C) <2012>  <Marchegiano Danilo>
*
* This file is part of RpyConfig.
*
* RpyConfig is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>
*/

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rpyconfig;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.lang.String;
import javax.swing.JButton;

/**
 *
 * @author d4n1x
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
    private arrayMaker generalArr = null;
    private arrayMaker monitorArr = null;
    private arrayMaker codecArr = null;
    private arrayMaker bootArr = null;
    private arrayMaker overclockArr = null;
    private arrayMaker nowaranty = null;
    
    public Home() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RpyConfig");
        setIconImages(null);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpyconfig/logo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpyconfig/BMonitor.png"))); // NOI18N
        jButton1.setAlignmentY(0.0F);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monitor(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 141, 159, 159));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpyconfig/BCodec.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codec(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 141, 159, 159));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpyconfig/BBoot.png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boot(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 141, 159, 159));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpyconfig/BOverK.png"))); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                overclock(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 141, 159, 159));

        jButton5.setText("Exit");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 328, 90, -1));

        jButton6.setText("Info");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Info(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 328, 90, -1));

        jButton7.setText("Create");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                create(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 328, 90, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 312, 813, 10));

        jButton8.setText("Help");
        jButton8.setEnabled(false);
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 328, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit
        System.exit(0);
    }//GEN-LAST:event_exit

    private void Info(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Info
        Info inf = new Info();
        inf.main(null);
    }//GEN-LAST:event_Info

    private void monitor(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monitor
        monitorArr = new arrayMaker();
        Monitor monitor = new Monitor();
        monitor.main(monitorArr);
    }//GEN-LAST:event_monitor

    private void codec(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codec
        codecArr = new arrayMaker();
        Codec code = new Codec();
        code.main(codecArr);
    }//GEN-LAST:event_codec

    private void boot(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boot
        bootArr = new arrayMaker();
        Boot boot = new Boot();
        boot.main(bootArr);
    }//GEN-LAST:event_boot

    private void overclock(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_overclock
        overclockArr = new arrayMaker();
        nowaranty = new arrayMaker();
        Overclock overclock = new Overclock();
        overclock.main(overclockArr, nowaranty);
    }//GEN-LAST:event_overclock

    private void generatorArray(){
    
        ArrayList<String> arr;
        
        //Add Monitor
        if(monitorArr != null){
            arr= monitorArr.getArray();
            for(String el: arr){
                generalArr.addElement(el);
            }
        }
        
        //Add Codec
        if(codecArr != null){
            arr= codecArr.getArray();
            for(String el: arr){
                generalArr.addElement(el);
            }
        }
        
        //Add boot
        if(bootArr != null){
            arr= bootArr.getArray();
            for(String el: arr){
                generalArr.addElement(el);
            }
        }
        
        //Add overclock
        if(overclockArr != null){
            arr= overclockArr.getArray();
            for(String el: arr){
                generalArr.addElement(el);
            }
        }
        
        //Add nowaranty
        if(nowaranty != null){
            arr= nowaranty.getArray();
            for(String el: arr){
                generalArr.addElement(el);
            }
        }
    }
    
    private void create(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create
        generalArr = new arrayMaker();
        generatorArray();
        
        try {
            WriteOnFile wrt = new WriteOnFile(generalArr);
            new Succes().main(null);
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            new Error().main(null);
        }
    }//GEN-LAST:event_create
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                //new Advertences().main(null);
                Home start = new Home();
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    
                // Determine the new location of the window
                int w = start.getSize().width;
                int h = start.getSize().height;
                int x = (dim.width-w)/2;
                int y = (dim.height-h)/2;
    
                // Move the window
                start.setLocation(x, y);
                start.setVisible(true);
                start.repaint();
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
