/*
* Copyright (C) <2012>  <Marchegiano Danilo>
*
* This file is part of RpyConfig.
*
* RpyConfig is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>
*/

package rpyconfig;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author d4n1x
 */
public class Nowaranty extends javax.swing.JFrame {

    
    static private Nowaranty nowa = new Nowaranty();
    static private arrayMaker array;
    /**
     * Creates new form nowaranty
     */
    public Nowaranty() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        over_voltage = new javax.swing.JTextField();
        over_voltage_sdram = new javax.swing.JTextField();
        over_voltage_sdram_c = new javax.swing.JTextField();
        over_voltage_sdram_i = new javax.swing.JTextField();
        over_voltage_sdram_p = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ckover_voltage_min = new javax.swing.JCheckBox();
        over_voltage_min = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ckover_voltage = new javax.swing.JCheckBox();
        ckover_voltage_sdram = new javax.swing.JCheckBox();
        ckover_voltage_sdram_c = new javax.swing.JCheckBox();
        ckover_voltage_sdram_i = new javax.swing.JCheckBox();
        ckover_voltage_sdram_p = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("WARNING !!! This parameter allow your warranty");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel2.setText("Advanced overclock settings");

        over_voltage.setEnabled(false);

        over_voltage_sdram.setEnabled(false);

        over_voltage_sdram_c.setEnabled(false);

        over_voltage_sdram_i.setEnabled(false);

        over_voltage_sdram_p.setEnabled(false);

        jButton1.setText("Ok");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ok(evt);
            }
        });

        jLabel3.setText("V");

        jLabel4.setText("V");

        jLabel5.setText("V");

        jLabel6.setText("V");

        jLabel7.setText("V");

        ckover_voltage_min.setText("Minimum value of over voltage used for dynamic clocking:");
        ckover_voltage_min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                overvoltageminOnOff(evt);
            }
        });

        over_voltage_min.setEnabled(false);

        jLabel9.setText("V");

        ckover_voltage.setText("Over voltage ARM/GPU core (Default 0):");
        ckover_voltage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                over_voltageOnOff(evt);
            }
        });

        ckover_voltage_sdram.setText("Set over voltage sdram:");
        ckover_voltage_sdram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                overvoltagesdramOnOff(evt);
            }
        });

        ckover_voltage_sdram_c.setText("SDRAM C controller over voltage adjust:");
        ckover_voltage_sdram_c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                overvoltagesdramcOnOff(evt);
            }
        });

        ckover_voltage_sdram_i.setText("SDRAM I controller over  voltage adjust:");
        ckover_voltage_sdram_i.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                overvoltagesdramiOnOff(evt);
            }
        });

        ckover_voltage_sdram_p.setText("SDRAM P controller voltage adjust:");
        ckover_voltage_sdram_p.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                overvoltagesdrampOnOff(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ckover_voltage)
                                        .addComponent(ckover_voltage_sdram)
                                        .addComponent(ckover_voltage_sdram_c)
                                        .addComponent(ckover_voltage_sdram_i)
                                        .addComponent(ckover_voltage_sdram_p))
                                    .addGap(185, 185, 185)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(over_voltage_sdram_p, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(over_voltage_sdram, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(over_voltage_sdram_c, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(over_voltage_sdram_i, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(over_voltage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ckover_voltage_min)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(over_voltage_min, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(over_voltage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(ckover_voltage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckover_voltage_min)
                    .addComponent(over_voltage_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(over_voltage_sdram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(ckover_voltage_sdram))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(over_voltage_sdram_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(ckover_voltage_sdram_c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(over_voltage_sdram_i, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(ckover_voltage_sdram_i))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(over_voltage_sdram_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ckover_voltage_sdram_p)
                        .addGap(12, 12, 12)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ok(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok
        
        String vover_voltage = null;
        String vover_voltage_min = null;
        String vover_voltage_sdram = null;
        String vover_voltage_sdram_c = null;
        String vover_voltage_sdram_i = null;
        String vover_voltage_sdram_p = null;
        
        /*ckover_voltage, ckover_voltage_min, ckover_voltage_sdram, ckover_voltage_sdram_c, ckover_voltage_sdram_i, ckover_voltage_sdram_p*/
        
        if(ckover_voltage.isSelected()){
            vover_voltage = "over_voltage=" + over_voltage.getText();
        }
        
        if(ckover_voltage_min.isSelected()){
            vover_voltage_min = "over_voltage_min=" + over_voltage_min.getText();
        }
        
        if(ckover_voltage_sdram.isSelected()){
            vover_voltage_sdram = "over_voltage_sdram=" + over_voltage_sdram.getText();
        }
        
        if(ckover_voltage_sdram_c.isSelected()){
            vover_voltage_sdram_c = "over_voltage_sdram_c=" + over_voltage_sdram_c.getText();
        }
        
        if(ckover_voltage_sdram_i.isSelected()){
            vover_voltage_sdram_i = "over_voltage_sdram_i=" + over_voltage_sdram_i.getText();
        }
        
        if(ckover_voltage_sdram_p.isSelected()){
            vover_voltage_sdram_p = "over_voltage_sdram_p=" + over_voltage_sdram_p.getText();
        }
        
        if(vover_voltage != null) array.addElement(vover_voltage);
        if(vover_voltage_min != null) array.addElement(vover_voltage_min);
        if(vover_voltage_sdram != null) array.addElement(vover_voltage_sdram);
        if(vover_voltage_sdram_c != null) array.addElement(vover_voltage_sdram_c);
        if(vover_voltage_sdram_i != null) array.addElement(vover_voltage_sdram_i);
        if(vover_voltage_sdram_p != null) array.addElement(vover_voltage_sdram_p);
        
        nowa.setVisible(false);
    }//GEN-LAST:event_ok

    private void over_voltageOnOff(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_over_voltageOnOff
        if(ckover_voltage.isSelected()){
            over_voltage.setEnabled(true);
        }else over_voltage.setEnabled(false);
        over_voltage.repaint();
    }//GEN-LAST:event_over_voltageOnOff

    private void overvoltageminOnOff(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_overvoltageminOnOff
        if(ckover_voltage_min.isSelected()){
            over_voltage_min.setEnabled(true);
        }else over_voltage_min.setEnabled(false);
        over_voltage_min.repaint();
    }//GEN-LAST:event_overvoltageminOnOff

    private void overvoltagesdramOnOff(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_overvoltagesdramOnOff
        if(ckover_voltage_sdram.isSelected()){
            over_voltage_sdram.setEnabled(true);
        }else over_voltage_sdram.setEnabled(false);
        over_voltage_sdram.repaint();        
    }//GEN-LAST:event_overvoltagesdramOnOff

    private void overvoltagesdramcOnOff(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_overvoltagesdramcOnOff
        if(ckover_voltage_sdram_c.isSelected()){
            over_voltage_sdram_c.setEnabled(true);
        }else over_voltage_sdram_c.setEnabled(false);
        over_voltage_sdram_c.repaint();
    }//GEN-LAST:event_overvoltagesdramcOnOff

    private void overvoltagesdramiOnOff(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_overvoltagesdramiOnOff
        if(ckover_voltage_sdram_i.isSelected()){
            over_voltage_sdram_i.setEnabled(true);
        }else over_voltage_sdram_i.setEnabled(false);
        over_voltage_sdram_i.repaint();
    }//GEN-LAST:event_overvoltagesdramiOnOff

    private void overvoltagesdrampOnOff(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_overvoltagesdrampOnOff
        if(ckover_voltage_sdram_p.isSelected()){
            over_voltage_sdram_p.setEnabled(true);
        }else over_voltage_sdram_p.setEnabled(false);
        over_voltage_sdram_p.repaint();
    }//GEN-LAST:event_overvoltagesdrampOnOff
  
    /**
     * @param args the command line arguments
     */
    public static void main(arrayMaker nomkArray) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nowaranty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nowaranty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nowaranty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nowaranty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        array = nomkArray;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    
                // Determine the new location of the window
                int w = nowa.getSize().width;
                int h = nowa.getSize().height;
                int x = (dim.width-w)/2;
                int y = (dim.height-h)/2;
    
                // Move the window
                nowa.setLocation(x, y);
                nowa.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ckover_voltage;
    private javax.swing.JCheckBox ckover_voltage_min;
    private javax.swing.JCheckBox ckover_voltage_sdram;
    private javax.swing.JCheckBox ckover_voltage_sdram_c;
    private javax.swing.JCheckBox ckover_voltage_sdram_i;
    private javax.swing.JCheckBox ckover_voltage_sdram_p;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField over_voltage;
    private javax.swing.JTextField over_voltage_min;
    private javax.swing.JTextField over_voltage_sdram;
    private javax.swing.JTextField over_voltage_sdram_c;
    private javax.swing.JTextField over_voltage_sdram_i;
    private javax.swing.JTextField over_voltage_sdram_p;
    // End of variables declaration//GEN-END:variables
}
